### ISSUE TITLE
Fail benchmarks task when return value is non zero

### ISSUE THREAD

**Issue by rengolin** [plaidml/tpp-mlir#273]
The benchmark job doesn't return failures. When a new leak appeared in the MLIR execution, the job didn't fail. Luckily, I was looking at the output and saw it and we know what it's about, this time.

Make the job fail on error by returning the return value to the shell. This should be a problem in the python harness when running the `tpp-run`.

@adam-smnk

**Comment by rengolin** [comment]
`bench_simple_copy`:

```
=================================================================
==137325==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 415236096 byte(s) in 99 object(s) allocated from:
    #0 0x55fdc5d53709 in malloc (/home/rengolin/devel/intel/tpp-mlir/build/bin/bench_simple_copy+0xe1709) (BuildId: b99a932102effd01bed5349cde634ba77cbb8787)
    #1 0x55fdc5d9ba22 in Tensor<float>::alloc() /home/rengolin/devel/intel/tpp-mlir/benchmarks/simple_copy/../include/Tensor.h:33:17
    #2 0x55fdc5d9ba22 in Tensor<float>::operator=(Tensor<float> const&) /home/rengolin/devel/intel/tpp-mlir/benchmarks/simple_copy/../include/Tensor.h:66:5
    #3 0x55fdc5d9ba22 in SimpleCopyKernel<float>::runRef(std::vector<Tensor<float>, std::allocator<Tensor<float> > >&) /home/rengolin/devel/intel/tpp-mlir/benchmarks/simple_copy/simple_copy.cpp:15:12
    #4 0x55fdc5d9ba22 in Benchmark<SimpleCopyKernel<float>, float>::run() /home/rengolin/devel/intel/tpp-mlir/benchmarks/simple_copy/../include/Bench.h:76:16
    #5 0x55fdc5d9aad7 in main /home/rengolin/devel/intel/tpp-mlir/benchmarks/simple_copy/simple_copy.cpp:60:9
    #6 0x7f78c8c1c28f  (/usr/lib/libc.so.6+0x2328f) (BuildId: 1e94beb079e278ac4f2c8bce1f53091548ea1584)

Direct leak of 4194304 byte(s) in 1 object(s) allocated from:
    #0 0x55fdc5d53709 in malloc (/home/rengolin/devel/intel/tpp-mlir/build/bin/bench_simple_copy+0xe1709) (BuildId: b99a932102effd01bed5349cde634ba77cbb8787)
    #1 0x55fdc5d9c52e in Tensor<float>::alloc() /home/rengolin/devel/intel/tpp-mlir/benchmarks/simple_copy/../include/Tensor.h:33:17
    #2 0x55fdc5d9c52e in Tensor<float>::Tensor(Tensor<float> const&) /home/rengolin/devel/intel/tpp-mlir/benchmarks/simple_copy/../include/Tensor.h:58:5
    #3 0x55fdc5d9a8d3 in void std::_Construct<Tensor<float>, Tensor<float> const&>(Tensor<float>*, Tensor<float> const&) /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/12.2.0/../../../../include/c++/12.2.0/bits/stl_construct.h:119:25
    #4 0x55fdc5d9a8d3 in Tensor<float>* std::__do_uninit_copy<Tensor<float> const*, Tensor<float>*>(Tensor<float> const*, Tensor<float> const*, Tensor<float>*) /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/12.2.0/../../../../include/c++/12.2.0/bits/stl_uninitialized.h:120:6
    #5 0x55fdc5d9a8d3 in Tensor<float>* std::__uninitialized_copy<false>::__uninit_copy<Tensor<float> const*, Tensor<float>*>(Tensor<float> const*, Tensor<float> const*, Tensor<float>*) /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/12.2.0/../../../../include/c++/12.2.0/bits/stl_uninitialized.h:137:11
    #6 0x55fdc5d9a8d3 in Tensor<float>* std::uninitialized_copy<Tensor<float> const*, Tensor<float>*>(Tensor<float> const*, Tensor<float> const*, Tensor<float>*) /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/12.2.0/../../../../include/c++/12.2.0/bits/stl_uninitialized.h:184:14
    #7 0x55fdc5d9a8d3 in Tensor<float>* std::__uninitialized_copy_a<Tensor<float> const*, Tensor<float>*, Tensor<float> >(Tensor<float> const*, Tensor<float> const*, Tensor<float>*, std::allocator<Tensor<float> >&) /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/12.2.0/../../../../include/c++/12.2.0/bits/stl_uninitialized.h:372:14
    #8 0x55fdc5d9a8d3 in void std::vector<Tensor<float>, std::allocator<Tensor<float> > >::_M_range_initialize<Tensor<float> const*>(Tensor<float> const*, Tensor<float> const*, std::forward_iterator_tag) /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/12.2.0/../../../../include/c++/12.2.0/bits/stl_vector.h:1690:6
    #9 0x55fdc5d9a8d3 in std::vector<Tensor<float>, std::allocator<Tensor<float> > >::vector(std::initializer_list<Tensor<float> >, std::allocator<Tensor<float> > const&) /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/12.2.0/../../../../include/c++/12.2.0/bits/stl_vector.h:677:2
    #10 0x55fdc5d9a8d3 in main /home/rengolin/devel/intel/tpp-mlir/benchmarks/simple_copy/simple_copy.cpp:46:16
    #11 0x7f78c8c1c28f  (/usr/lib/libc.so.6+0x2328f) (BuildId: 1e94beb079e278ac4f2c8bce1f53091548ea1584)

Direct leak of 4194304 byte(s) in 1 object(s) allocated from:
    #0 0x55fdc5d53709 in malloc (/home/rengolin/devel/intel/tpp-mlir/build/bin/bench_simple_copy+0xe1709) (BuildId: b99a932102effd01bed5349cde634ba77cbb8787)
    #1 0x55fdc5d9a9fc in Tensor<float>::alloc() /home/rengolin/devel/intel/tpp-mlir/benchmarks/simple_copy/../include/Tensor.h:33:17
    #2 0x55fdc5d9a9fc in Tensor<float>::operator=(Tensor<float> const&) /home/rengolin/devel/intel/tpp-mlir/benchmarks/simple_copy/../include/Tensor.h:66:5
    #3 0x55fdc5d9a9fc in SimpleCopyKernel<float>::runRef(std::vector<Tensor<float>, std::allocator<Tensor<float> > >&) /home/rengolin/devel/intel/tpp-mlir/benchmarks/simple_copy/simple_copy.cpp:15:12
    #4 0x55fdc5d9a9fc in Benchmark<SimpleCopyKernel<float>, float>::warmup() /home/rengolin/devel/intel/tpp-mlir/benchmarks/simple_copy/../include/Bench.h:65:14
    #5 0x55fdc5d9a9fc in main /home/rengolin/devel/intel/tpp-mlir/benchmarks/simple_copy/simple_copy.cpp:52:9
    #6 0x7f78c8c1c28f  (/usr/lib/libc.so.6+0x2328f) (BuildId: 1e94beb079e278ac4f2c8bce1f53091548ea1584)

SUMMARY: AddressSanitizer: 423624704 byte(s) leaked in 101 allocation(s).
```

**Comment by rengolin** [comment]
Fixed in CI. The issue was that the driver was piping the results to the plotting script, so the return value was from the script, not the benchmark. Now I redirect the output to a file and then cat the file to the script, which fails if the driver fails.
